# Generated by Django 5.2.8 on 2025-11-09 13:21

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_create_homepage"),
        ("wagtailcore", "0095_groupsitepermission"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "subtitle",
                    models.CharField(
                        blank=True, help_text="Optional page subtitle", max_length=250
                    ),
                ),
                (
                    "introduction",
                    wagtail.fields.RichTextField(
                        blank=True, help_text="Optional introduction text for the page"
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [("richtext_section", 2), ("gallery", 6), ("cta_button", 9)],
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {"required": False}),
                            1: ("wagtail.blocks.RichTextBlock", (), {}),
                            2: (
                                "wagtail.blocks.StructBlock",
                                [[("heading", 0), ("body", 1)]],
                                {},
                            ),
                            3: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                            4: (
                                "wagtail.blocks.StructBlock",
                                [[("image", 3), ("caption", 0)]],
                                {},
                            ),
                            5: ("wagtail.blocks.ListBlock", (4,), {}),
                            6: ("wagtail.blocks.StructBlock", [[("images", 5)]], {}),
                            7: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Text for the button",
                                    "max_length": 255,
                                    "required": True,
                                },
                            ),
                            8: (
                                "wagtail.blocks.URLBlock",
                                (),
                                {
                                    "help_text": "URL for the button link",
                                    "required": True,
                                },
                            ),
                            9: (
                                "wagtail.blocks.StructBlock",
                                [[("button_text", 7), ("button_link", 8)]],
                                {},
                            ),
                        },
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="ContactPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "subtitle",
                    models.CharField(
                        blank=True, help_text="Optional page subtitle", max_length=250
                    ),
                ),
                (
                    "introduction",
                    wagtail.fields.RichTextField(
                        blank=True, help_text="Optional introduction text for the page"
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [("contact_info", 4), ("cta_button", 7)],
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {}),
                            1: ("wagtail.blocks.TextBlock", (), {}),
                            2: ("wagtail.blocks.EmailBlock", (), {}),
                            3: ("wagtail.blocks.TextBlock", (), {"required": False}),
                            4: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("office_name", 0),
                                        ("address", 1),
                                        ("phone", 0),
                                        ("email", 2),
                                        ("map_embed", 3),
                                    ]
                                ],
                                {},
                            ),
                            5: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Text for the button",
                                    "max_length": 255,
                                    "required": True,
                                },
                            ),
                            6: (
                                "wagtail.blocks.URLBlock",
                                (),
                                {
                                    "help_text": "URL for the button link",
                                    "required": True,
                                },
                            ),
                            7: (
                                "wagtail.blocks.StructBlock",
                                [[("button_text", 5), ("button_link", 6)]],
                                {},
                            ),
                        },
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="CulturePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "subtitle",
                    models.CharField(
                        blank=True, help_text="Optional page subtitle", max_length=250
                    ),
                ),
                (
                    "introduction",
                    wagtail.fields.RichTextField(
                        blank=True, help_text="Optional introduction text for the page"
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [("culture", 4), ("richtext_section", 7), ("gallery", 11)],
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Name of the culture",
                                    "max_length": 100,
                                    "required": True,
                                },
                            ),
                            1: (
                                "wagtail.blocks.TextBlock",
                                (),
                                {
                                    "help_text": "Description of the culture",
                                    "required": True,
                                },
                            ),
                            2: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {
                                    "help_text": "Image representing the culture",
                                    "required": True,
                                },
                            ),
                            3: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("music", "Music"),
                                        ("art", "Art"),
                                        ("food", "Food"),
                                        ("traditions", "Traditions"),
                                        ("festivals", "Festivals"),
                                    ],
                                    "help_text": "Category of the culture",
                                },
                            ),
                            4: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("culture_name", 0),
                                        ("culture_description", 1),
                                        ("culture_image", 2),
                                        ("category", 3),
                                    ]
                                ],
                                {},
                            ),
                            5: ("wagtail.blocks.CharBlock", (), {"required": False}),
                            6: ("wagtail.blocks.RichTextBlock", (), {}),
                            7: (
                                "wagtail.blocks.StructBlock",
                                [[("heading", 5), ("body", 6)]],
                                {},
                            ),
                            8: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                            9: (
                                "wagtail.blocks.StructBlock",
                                [[("image", 8), ("caption", 5)]],
                                {},
                            ),
                            10: ("wagtail.blocks.ListBlock", (9,), {}),
                            11: ("wagtail.blocks.StructBlock", [[("images", 10)]], {}),
                        },
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="DestinationsPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "subtitle",
                    models.CharField(
                        blank=True, help_text="Optional page subtitle", max_length=250
                    ),
                ),
                (
                    "introduction",
                    wagtail.fields.RichTextField(
                        blank=True, help_text="Optional introduction text for the page"
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [("destination", 4), ("richtext_section", 7), ("gallery", 11)],
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Name of the destination",
                                    "max_length": 100,
                                    "required": True,
                                },
                            ),
                            1: (
                                "wagtail.blocks.TextBlock",
                                (),
                                {
                                    "help_text": "Description of the destination",
                                    "required": True,
                                },
                            ),
                            2: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {
                                    "help_text": "Image of the destination",
                                    "required": True,
                                },
                            ),
                            3: (
                                "wagtail.blocks.TextBlock",
                                (),
                                {
                                    "help_text": "Embed code for the map",
                                    "required": False,
                                },
                            ),
                            4: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("destination_name", 0),
                                        ("destination_description", 1),
                                        ("destination_image", 2),
                                        ("map_embed", 3),
                                    ]
                                ],
                                {},
                            ),
                            5: ("wagtail.blocks.CharBlock", (), {"required": False}),
                            6: ("wagtail.blocks.RichTextBlock", (), {}),
                            7: (
                                "wagtail.blocks.StructBlock",
                                [[("heading", 5), ("body", 6)]],
                                {},
                            ),
                            8: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                            9: (
                                "wagtail.blocks.StructBlock",
                                [[("image", 8), ("caption", 5)]],
                                {},
                            ),
                            10: ("wagtail.blocks.ListBlock", (9,), {}),
                            11: ("wagtail.blocks.StructBlock", [[("images", 10)]], {}),
                        },
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="EventsPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "subtitle",
                    models.CharField(
                        blank=True, help_text="Optional page subtitle", max_length=250
                    ),
                ),
                (
                    "introduction",
                    wagtail.fields.RichTextField(
                        blank=True, help_text="Optional introduction text for the page"
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [("event", 6), ("richtext_section", 9), ("cta_button", 12)],
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {}),
                            1: ("wagtail.blocks.DateBlock", (), {}),
                            2: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                            3: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {"required": False},
                            ),
                            4: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("title", 0),
                                        ("date", 1),
                                        ("image", 2),
                                        ("link", 3),
                                    ]
                                ],
                                {},
                            ),
                            5: ("wagtail.blocks.ListBlock", (4,), {}),
                            6: ("wagtail.blocks.StructBlock", [[("events", 5)]], {}),
                            7: ("wagtail.blocks.CharBlock", (), {"required": False}),
                            8: ("wagtail.blocks.RichTextBlock", (), {}),
                            9: (
                                "wagtail.blocks.StructBlock",
                                [[("heading", 7), ("body", 8)]],
                                {},
                            ),
                            10: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Text for the button",
                                    "max_length": 255,
                                    "required": True,
                                },
                            ),
                            11: (
                                "wagtail.blocks.URLBlock",
                                (),
                                {
                                    "help_text": "URL for the button link",
                                    "required": True,
                                },
                            ),
                            12: (
                                "wagtail.blocks.StructBlock",
                                [[("button_text", 10), ("button_link", 11)]],
                                {},
                            ),
                        },
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="GalleryPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "subtitle",
                    models.CharField(
                        blank=True, help_text="Optional page subtitle", max_length=250
                    ),
                ),
                (
                    "introduction",
                    wagtail.fields.RichTextField(
                        blank=True, help_text="Optional introduction text for the page"
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [("gallery", 4), ("lightbox", 5)],
                        block_lookup={
                            0: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                            1: ("wagtail.blocks.CharBlock", (), {"required": False}),
                            2: (
                                "wagtail.blocks.StructBlock",
                                [[("image", 0), ("caption", 1)]],
                                {},
                            ),
                            3: ("wagtail.blocks.ListBlock", (2,), {}),
                            4: ("wagtail.blocks.StructBlock", [[("images", 3)]], {}),
                            5: ("wagtail.blocks.StructBlock", [[("gallery", 3)]], {}),
                        },
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="NewsPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "subtitle",
                    models.CharField(
                        blank=True, help_text="Optional page subtitle", max_length=250
                    ),
                ),
                (
                    "introduction",
                    wagtail.fields.RichTextField(
                        blank=True, help_text="Optional introduction text for the page"
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [("news", 5), ("cta_button", 8)],
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Title of the news article",
                                    "max_length": 150,
                                    "required": True,
                                },
                            ),
                            1: (
                                "wagtail.blocks.TextBlock",
                                (),
                                {
                                    "help_text": "Summary of the news article",
                                    "required": True,
                                },
                            ),
                            2: (
                                "wagtail.blocks.DateBlock",
                                (),
                                {
                                    "help_text": "Publication date of the news article",
                                    "required": True,
                                },
                            ),
                            3: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {
                                    "help_text": "Image for the news article",
                                    "required": False,
                                },
                            ),
                            4: (
                                "wagtail.blocks.URLBlock",
                                (),
                                {
                                    "help_text": "Link to the full news article",
                                    "required": True,
                                },
                            ),
                            5: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("news_title", 0),
                                        ("news_summary", 1),
                                        ("news_date", 2),
                                        ("news_image", 3),
                                        ("news_link", 4),
                                    ]
                                ],
                                {},
                            ),
                            6: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Text for the button",
                                    "max_length": 255,
                                    "required": True,
                                },
                            ),
                            7: (
                                "wagtail.blocks.URLBlock",
                                (),
                                {
                                    "help_text": "URL for the button link",
                                    "required": True,
                                },
                            ),
                            8: (
                                "wagtail.blocks.StructBlock",
                                [[("button_text", 6), ("button_link", 7)]],
                                {},
                            ),
                        },
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="PlanYourTripPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "subtitle",
                    models.CharField(
                        blank=True, help_text="Optional page subtitle", max_length=250
                    ),
                ),
                (
                    "introduction",
                    wagtail.fields.RichTextField(
                        blank=True, help_text="Optional introduction text for the page"
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            ("trip_guide", 5),
                            ("richtext_section", 7),
                            ("cta_button", 10),
                        ],
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {}),
                            1: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"help_text": "e.g., 3-Day Trip", "required": False},
                            ),
                            2: ("wagtail.blocks.RichTextBlock", (), {}),
                            3: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                            4: (
                                "wagtail.documents.blocks.DocumentChooserBlock",
                                (),
                                {
                                    "help_text": "Optional downloadable guide",
                                    "required": False,
                                },
                            ),
                            5: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("itinerary_name", 0),
                                        ("duration", 1),
                                        ("description", 2),
                                        ("image", 3),
                                        ("pdf_download", 4),
                                    ]
                                ],
                                {},
                            ),
                            6: ("wagtail.blocks.CharBlock", (), {"required": False}),
                            7: (
                                "wagtail.blocks.StructBlock",
                                [[("heading", 6), ("body", 2)]],
                                {},
                            ),
                            8: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Text for the button",
                                    "max_length": 255,
                                    "required": True,
                                },
                            ),
                            9: (
                                "wagtail.blocks.URLBlock",
                                (),
                                {
                                    "help_text": "URL for the button link",
                                    "required": True,
                                },
                            ),
                            10: (
                                "wagtail.blocks.StructBlock",
                                [[("button_text", 8), ("button_link", 9)]],
                                {},
                            ),
                        },
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.AddField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("hero_banner", 5),
                    ("featured_destinations", 12),
                    ("upcoming_events", 16),
                    ("richtext_section", 19),
                    ("cta_button", 22),
                ],
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Title for the hero banner",
                            "max_length": 100,
                            "required": True,
                        },
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Subtitle for the hero banner",
                            "max_length": 250,
                            "required": False,
                        },
                    ),
                    2: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"help_text": "Image for the hero banner", "required": True},
                    ),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Call to action text",
                            "max_length": 50,
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"help_text": "Call to action link", "required": False},
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("hero_title", 0),
                                ("hero_subtitle", 1),
                                ("hero_image", 2),
                                ("cta_text", 3),
                                ("cta_link", 4),
                            ]
                        ],
                        {},
                    ),
                    6: ("wagtail.blocks.CharBlock", (), {}),
                    7: ("wagtail.blocks.TextBlock", (), {}),
                    8: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    9: ("wagtail.blocks.PageChooserBlock", (), {"required": False}),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 6), ("description", 7), ("image", 8), ("link", 9)]],
                        {},
                    ),
                    11: ("wagtail.blocks.ListBlock", (10,), {}),
                    12: ("wagtail.blocks.StructBlock", [[("destinations", 11)]], {}),
                    13: ("wagtail.blocks.DateBlock", (), {}),
                    14: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 6), ("date", 13), ("image", 8), ("link", 9)]],
                        {},
                    ),
                    15: ("wagtail.blocks.ListBlock", (14,), {}),
                    16: ("wagtail.blocks.StructBlock", [[("events", 15)]], {}),
                    17: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    18: ("wagtail.blocks.RichTextBlock", (), {}),
                    19: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 17), ("body", 18)]],
                        {},
                    ),
                    20: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Text for the button",
                            "max_length": 255,
                            "required": True,
                        },
                    ),
                    21: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"help_text": "URL for the button link", "required": True},
                    ),
                    22: (
                        "wagtail.blocks.StructBlock",
                        [[("button_text", 20), ("button_link", 21)]],
                        {},
                    ),
                },
                default=[],
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="introduction",
            field=wagtail.fields.RichTextField(
                blank=True, help_text="Optional introduction text for the page"
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="subtitle",
            field=models.CharField(
                blank=True, help_text="Optional page subtitle", max_length=250
            ),
        ),
    ]
